name: Fedex Cron setup
    
on:
  schedule:
    - cron: "20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.SECRET_TOKEN}}
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.6
      - name: geckodriver/firefox
        run: |
          echo "geckodriver/firefox"
          which geckodriver
          geckodriver --version
          which firefox
          firefox --version
      - name: install requirements
        run: |
          pip install -r requirements.txt
      - name: run cron script
        run: |
          python test.py
      - name: set global variable
        run: |
          git config --global user.name 'steveoni'
          git config --global user.email 'steohenoni2@gmail.com'
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git status
          git add .
          git commit -m "Auto fetch data and update"
          git fetch origin main
          git push origin HEAD:main
